FROM python:3.12-slim-bullseye

WORKDIR /app

RUN apt update && apt install -y git

COPY requirements.prod.txt requirements.dev.txt
RUN pip install poetry && \
    poetry config virtualenvs.create false

COPY requirements.prod.txt requirements.dev.txt pyproject.toml poetry.lock ./
RUN \
    # pip install -r requirements.prod.txt && \
    # pip install -r requirements.dev.txt
    poetry install --no-interaction --no-ansi

COPY . .

# CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "wsgi:app"]
# CMD ["gunicorn", "--config", "gunicorn_config.py", "wsgi:app"]
